### ISSUE TITLE
server start times out

### ISSUE THREAD

**Issue by brentley** [pritunl/pritunl-node#1]
[summer-plains-9718][2015-02-18 17:10:22,544][ERROR] Exception on /server/54e50db713c99b12d867ab56/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pritunl/handlers/server.py", line 666, in server_operation_put
    svr.start()
  File "/usr/lib/python2.7/site-packages/pritunl/server/server.py", line 765, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('54e50db713c99b12d867ab56')}

Full disclosure, I had pritunl working on centos7 last week, but now, when I'm trying to productionize it on a host, I get this timeout. I can't find what might be wrong.

**Comment by zachhuff386** [comment]
Server start timed out occurs when none of the hosts respond to a start event. On Enterprise edition with multiple host's it could be caused by all of the server's hosts being offline check that the hosts are listed as Online in the Hosts section. It could also be an issue starting the vpn server check the server output for errors.

**Comment by brentley** [comment]
the one change I can think of that I made was I upgraded to enterprise edition. 

I currently only have one host, and it shows online. 

![pritunl](https://cloud.githubusercontent.com/assets/243984/6258205/aaa45178-b794-11e4-821c-581b7e71d63f.png)
![pritunl](https://cloud.githubusercontent.com/assets/243984/6258227/d7d6d756-b794-11e4-9c62-8d584b8e034b.png)
![pritunl](https://cloud.githubusercontent.com/assets/243984/6258243/fb06ac24-b794-11e4-8b41-fa02c2967573.png)

**Comment by zachhuff386** [comment]
Check the output of `pritunl logs` and `cat /var/log/pritunl.log` for errors that occur when db is offline. Check the version of mongodb `mongod --version` version 2.6 or greater is needed.

**Comment by brentley** [comment]
# mongod --version
db version v2.6.5
2015-02-18T17:47:34.494-0500 git version: nogitversion
2015-02-18T17:47:34.494-0500 OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

# pritunl logs
(snip older similar entries)
[summer-plains-9718][2015-02-18 17:45:52,271][ERROR] Exception on /server/54e5159e13c99b34562764df/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pritunl/handlers/server.py", line 666, in server_operation_put
    svr.start()
  File "/usr/lib/python2.7/site-packages/pritunl/server/server.py", line 765, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('54e5159e13c99b34562764df')}

# cat /var/log/pritunl.log
[undefined][2015-02-18 17:25:06,790][INFO] Setting db version
  new_ver = '1.0.513.37'
  cur_ver = u'1.0.513.37'
[undefined][2015-02-18 17:41:09,038][INFO] Setting db version
  new_ver = '1.0.513.37'
  cur_ver = u'1.0.513.37'
[undefined][2015-02-18 17:45:36,336][INFO] Setting db version
  new_ver = '1.0.513.37'
  cur_ver = u'1.0.513.37'

**Comment by brentley** [comment]
whoa. sorry about the auto-markup making the commands super large.

**Comment by zachhuff386** [comment]
It's possible there is some issue with tailable cursors on your database which are used for the event system, try renaming a user or server and the name should update without needed to refresh the page. What Linux distribution and version are you using?

**Comment by brentley** [comment]
cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)

It seems like when I rename stuff, I have to refresh the page to see the
change take effect.



--------
Brent
--------

**Comment by brentley** [comment]
okay, I wiped the db, reinstalled pritunl, and reconfigured the server. it now starts successfully. 

Now i'll enter the enterprise key and see if I can break it.

**Comment by brentley** [comment]
alright. I don't know what was wrong. now it's working fine. sorry for the noise.  I have a couple of other questions, but I'll open new issues.

**Comment by zachhuff386** [comment]
Okay, no problem. Please use the https://github.com/pritunl/pritunl repository for new issues.
